### ISSUE TITLE
[Request] Add option to add a margin on the left

### ISSUE THREAD

**Issue by Rknegt** [AssisrMatheus/sidebar-markdown-notes#2]
There is little to no margin on the left side as show in the picture. 
Could there be an option to increase the left margin a little?

![small-left-margin](https://user-images.githubusercontent.com/51092169/98160193-20651300-1ede-11eb-8f98-9762baaf9143.png)

**Comment by AssisrMatheus** [comment]
That is totally possible to do. I'll make sure to add it this weekend!

**Comment by AssisrMatheus** [comment]
The option `sidebar-markdown-notes.leftMargin` is now available on version 1.0.4. Thank you for the suggestioN!
