### ISSUE TITLE
Support for checkbox clicking

### ISSUE THREAD

**Issue by giubatt** [AssisrMatheus/sidebar-markdown-notes#21]
I wanted to use this to make a list of TODOs and notes of work that I have to get done, but I just noticed it's not possible to check a checkbox by clicking on it, I would have to manually edit the markdown and change it from `[ ]` to `[x]`

**Comment by mndscp** [comment]
Definitely this! This extension is great, I can see my collegues asking about what it is when they see it. But not being able to tick off points on a to-do bullet point list makes it impossible to use. Can you introduce that feature?

**Comment by zbarbuto** [comment]
FTR this was implemented in #27 and is to be released in 1.1.0 as per #29 

Just some issues with CI it seems that need to be resolved for it to be rolled out.

**Comment by AssisrMatheus** [comment]
1.1.0 Should be available on both marketplaces now
