### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [AssisrMatheus/sidebar-markdown-notes#3]
Please add this useful extension to the [Open VSX Registry](https://open-vsx.org/?search=notes).

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by yujikiriki** [comment]
Open VSX is an open-source registry for VS Code extensions. It can be used by any development environment that supports such extensions. See this [article](https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php) for more information.

It would be cool if this marvellous extension is available in OpenVSX.

the guide to publish it can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

There is a [Github Action](https://github.com/HaaLeo/publish-vscode-extension#readme) to publish the extension to OpenVSX that can be used too.

**Comment by AssisrMatheus** [comment]
Thanks for the info guys!

I pushed a new version `1.0.4` and also added publishing to open vsx to github actions.

It's already available at https://open-vsx.org/extension/assisrMatheus/sidebar-markdown-notes
