### ISSUE TITLE
Please add tags for the released versions

### ISSUE THREAD

**Issue by GitMensch** [AssisrMatheus/sidebar-markdown-notes#4]
As you likely know you can tag old commits, too, and you can even have the correct date for them.
As I'm a huge fan of good versioning and like this extension...

```sh
# set the HEAD to the old commit that we want to tag
git checkout 124b52adafdf8c91fdf0118119db733932ae9d1d

# temporarily set the date to the date of the HEAD commit, and add the tag
GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" \
git tag -a v1.0.0 -m"Initial Release"

# push to GitHub
git push origin v1.0,0

# other versions, same fun

git checkout d08e107dfa05ce8914963ac04e2ec0bce9b854f1
GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" \
git tag -a v1.0.1 -m"First update"
git push origin v1.0,1

git checkout 722dedf7e120019e39da445b764bd34b0df6e60f
GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" \
git tag -a v1.0.2 -m"Fixed a bug with the loaded content"
git push origin v1.0,2

git checkout 582874e0ff2e897ed449d5b433aaafe90bf35e09
GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" \
git tag -a v1.0.3 -m"Fixed a bug with a debounced function"
git push origin v1.0,3

# set HEAD back to whatever you want it to be
git checkout master
```

And of course: please tag new versions (in an ideal world you can use CI to publish to all market places / vsix registries you like to by just committing a tag that matches with `v[:number:]\.[:number:]\.[:number:]`.

_______________
This issue's recept was created with the help the commit history and https://stackoverflow.com/a/4404197/5027456 + https://stackoverflow.com/a/21759466/5027456

**Comment by AssisrMatheus** [comment]
I added tags now. Seems like the `GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)"` didn't work unfortunately. But I'll start creating tags correctly from now on
